sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"

install:
  - npm install -g grunt-cli bower
  - node --version
  - npm --version
  - git --version
  - bower --version
  - npm install

os:
  - linux

script:
  - grunt CI
