language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'

before_install: npm install -g grunt-cli
after_script: NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
